### ISSUE TITLE
Complains about faraday

### ISSUE THREAD

**Issue by trivektor** [archan937/motion-bundler#11]
Hi,

I'm using motion-bundler for my project. I setup motion-bundler according to the README instructions. However, I got the following errors when I 'rake' the app

cannot load such file -- /Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/faraday-0.8.7/lib/faraday/request/timeout
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/motion-bundler-0.2.1/lib/motion-bundler/require/mocker/hooks.rb:21:in `require'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/motion-bundler-0.2.1/lib/motion-bundler/require/mocker/hooks.rb:21:in`require_with_mb_mock'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/motion-bundler-0.2.1/lib/motion-bundler/require/tracer/hooks.rb:33:in `block in require_with_mb_trace'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/motion-bundler-0.2.1/lib/motion-bundler/require/tracer/log.rb:42:in`register'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/motion-bundler-0.2.1/lib/motion-bundler/require/tracer/hooks.rb:32:in `require_with_mb_trace'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/motion-bundler-0.2.1/lib/motion-bundler/require/tracer/hooks.rb:66:in`autoload_with_mb_trace'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/faraday-0.8.7/lib/faraday.rb:77:in `block in autoload_all'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/faraday-0.8.7/lib/faraday.rb:76:in`each'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/faraday-0.8.7/lib/faraday.rb:76:in `autoload_all'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/faraday-0.8.7/lib/faraday/request.rb:16:in`class:Request'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/faraday-0.8.7/lib/faraday/request.rb:12:in `<module:Faraday>'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/faraday-0.8.7/lib/faraday/request.rb:1:in`<top (required)>'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/motion-bundler-0.2.1/lib/motion-bundler/require/mocker/hooks.rb:21:in `require'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/motion-bundler-0.2.1/lib/motion-bundler/require/mocker/hooks.rb:21:in`require_with_mb_mock'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/motion-bundler-0.2.1/lib/motion-bundler/require/tracer/hooks.rb:33:in `block in require_with_mb_trace'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/motion-bundler-0.2.1/lib/motion-bundler/require/tracer/log.rb:42:in`register'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/motion-bundler-0.2.1/lib/motion-bundler/require/tracer/hooks.rb:32:in `require_with_mb_trace'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/motion-bundler-0.2.1/lib/motion-bundler/require/tracer/hooks.rb:66:in`autoload_with_mb_trace'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/faraday-0.8.7/lib/faraday.rb:77:in `block in autoload_all'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/faraday-0.8.7/lib/faraday.rb:76:in`each'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/faraday-0.8.7/lib/faraday.rb:76:in `autoload_all'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/faraday-0.8.7/lib/faraday.rb:120:in`module:Faraday'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/faraday-0.8.7/lib/faraday.rb:1:in `<top (required)>'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/motion-bundler-0.2.1/lib/motion-bundler/require/mocker/hooks.rb:21:in`require'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/motion-bundler-0.2.1/lib/motion-bundler/require/mocker/hooks.rb:21:in `require_with_mb_mock'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/motion-bundler-0.2.1/lib/motion-bundler/require/tracer/hooks.rb:33:in`block in require_with_mb_trace'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/motion-bundler-0.2.1/lib/motion-bundler/require/tracer/log.rb:42:in `register'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/motion-bundler-0.2.1/lib/motion-bundler/require/tracer/hooks.rb:32:in`require_with_mb_trace'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/github_api-0.8.2/lib/github_api/connection.rb:3:in `<top (required)>'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/motion-bundler-0.2.1/lib/motion-bundler/require/mocker/hooks.rb:21:in`require'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/motion-bundler-0.2.1/lib/motion-bundler/require/mocker/hooks.rb:21:in `require_with_mb_mock'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/motion-bundler-0.2.1/lib/motion-bundler/require/tracer/hooks.rb:33:in`block in require_with_mb_trace'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/motion-bundler-0.2.1/lib/motion-bundler/require/tracer/log.rb:42:in `register'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/motion-bundler-0.2.1/lib/motion-bundler/require/tracer/hooks.rb:32:in`require_with_mb_trace'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/github_api-0.8.2/lib/github_api.rb:7:in `<top (required)>'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/motion-bundler-0.2.1/lib/motion-bundler/require/mocker/hooks.rb:21:in`require'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/motion-bundler-0.2.1/lib/motion-bundler/require/mocker/hooks.rb:21:in `require_with_mb_mock'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/motion-bundler-0.2.1/lib/motion-bundler/require/tracer/hooks.rb:33:in`block in require_with_mb_trace'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/motion-bundler-0.2.1/lib/motion-bundler/require/tracer/log.rb:42:in `register'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/motion-bundler-0.2.1/lib/motion-bundler/require/tracer/hooks.rb:32:in`require_with_mb_trace'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/bundler-1.2.4/lib/bundler/runtime.rb:68:in `block (2 levels) in require'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/bundler-1.2.4/lib/bundler/runtime.rb:66:in`each'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/bundler-1.2.4/lib/bundler/runtime.rb:66:in `block in require'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/bundler-1.2.4/lib/bundler/runtime.rb:55:in`each'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/bundler-1.2.4/lib/bundler/runtime.rb:55:in `require'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/bundler-1.2.4/lib/bundler.rb:128:in`require'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/motion-bundler-0.2.1/lib/motion-bundler.rb:83:in `block in tracer_require'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/motion-bundler-0.2.1/lib/motion-bundler/require.rb:14:in`block (2 levels) in mock_and_trace'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/motion-bundler-0.2.1/lib/motion-bundler/require.rb:21:in `block in trace'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/motion-bundler-0.2.1/lib/motion-bundler/require/tracer.rb:18:in`yield'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/motion-bundler-0.2.1/lib/motion-bundler/require.rb:20:in `trace'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/motion-bundler-0.2.1/lib/motion-bundler/require.rb:13:in`block in mock_and_trace'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/motion-bundler-0.2.1/lib/motion-bundler/require.rb:27:in `block in mock'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/motion-bundler-0.2.1/lib/motion-bundler/require/mocker.rb:13:in`yield'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/motion-bundler-0.2.1/lib/motion-bundler/require.rb:26:in `mock'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/motion-bundler-0.2.1/lib/motion-bundler/require.rb:12:in`mock_and_trace'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/motion-bundler-0.2.1/lib/motion-bundler.rb:80:in `tracer_require'
/Users/trivuong/.rvm/gems/ruby-1.9.3-p194/gems/motion-bundler-0.2.1/lib/motion-bundler.rb:23:in`block in setup'
/Library/RubyMotion/lib/motion/project/config.rb:108:in `call'
/Library/RubyMotion/lib/motion/project/config.rb:108:in`block in setup'
/Library/RubyMotion/lib/motion/project/config.rb:108:in `each'
/Library/RubyMotion/lib/motion/project/config.rb:108:in`setup'
/Library/RubyMotion/lib/motion/project/app.rb:64:in `config'
/Library/RubyMotion/lib/motion/project/app.rb:76:in`build'
/Library/RubyMotion/lib/motion/project/template/ios.rb:42:in `block (2 levels) in <top (required)>'
/Library/RubyMotion/lib/motion/project/template/ios.rb:55:in`block in <top (required)>'
Tasks: TOP => build:simulator
`

Here's my app's Gemfile and Rakefile

https://github.com/trivektor/Gitpad-Motion/blob/master/Gemfile
https://github.com/trivektor/Gitpad-Motion/blob/master/Rakefile

**Comment by hstove** [comment]
I'm having the same issue. Did anyone find any suggestions?

**Comment by loopj** [comment]
:+1: same issue

**Comment by loopj** [comment]
It looks like this is actually a bug in faraday, I've made a PR:
https://github.com/lostisland/faraday/pull/407

**Comment by keplersj** [comment]
I'm not sure how related my issue may be, but I am having issues requiring Faraday with RubyMotion 3:

Using MotionBundler Trace

```
bundle exec motion-bundler trace faraday
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.0/lib/faraday/adapter/em_synchrony.rb:6:in `<class:EMSynchrony>': uninitialized constant Faraday::Adapter::EMSynchrony::EMHttp (NameError)
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.0/lib/faraday/adapter/em_synchrony.rb:5:in `<class:Adapter>'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.0/lib/faraday/adapter/em_synchrony.rb:4:in `<module:Faraday>'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.0/lib/faraday/adapter/em_synchrony.rb:3:in `<top (required)>'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require/mocker/hooks.rb:21:in `require'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require/mocker/hooks.rb:21:in `require_with_mb_mock'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require/tracer/hooks.rb:33:in `block in require_with_mb_trace'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require/tracer/log.rb:42:in `register'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require/tracer/hooks.rb:32:in `require_with_mb_trace'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require/tracer/hooks.rb:66:in `autoload_with_mb_trace'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.0/lib/faraday/autoload.rb:27:in `block in autoload_all'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.0/lib/faraday/autoload.rb:26:in `each'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.0/lib/faraday/autoload.rb:26:in `autoload_all'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.0/lib/faraday/autoload.rb:53:in `<class:Adapter>'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.0/lib/faraday/autoload.rb:51:in `<module:Faraday>'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.0/lib/faraday/autoload.rb:1:in `<top (required)>'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require/mocker/hooks.rb:21:in `require'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require/mocker/hooks.rb:21:in `require_with_mb_mock'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require/tracer/hooks.rb:33:in `block in require_with_mb_trace'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require/tracer/log.rb:42:in `register'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require/tracer/hooks.rb:32:in `require_with_mb_trace'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.0/lib/faraday.rb:80:in `block in require_libs'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.0/lib/faraday.rb:79:in `each'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.0/lib/faraday.rb:79:in `require_libs'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.0/lib/faraday.rb:244:in `<module:Faraday>'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.0/lib/faraday.rb:16:in `<top (required)>'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require/mocker/hooks.rb:21:in `require'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require/mocker/hooks.rb:21:in `require_with_mb_mock'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require/tracer/hooks.rb:33:in `block in require_with_mb_trace'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require/tracer/log.rb:42:in `register'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require/tracer/hooks.rb:32:in `require_with_mb_trace'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/cli.rb:15:in `block in trace'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require.rb:14:in `block (2 levels) in mock_and_trace'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require.rb:21:in `block in trace'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require/tracer.rb:18:in `yield'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require.rb:20:in `trace'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require.rb:13:in `block in mock_and_trace'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require.rb:27:in `block in mock'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require/mocker.rb:13:in `yield'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require.rb:26:in `mock'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require.rb:12:in `mock_and_trace'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/cli.rb:14:in `trace'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/bin/motion-bundler:7:in `<top (required)>'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/bin/motion-bundler:23:in `load'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/bin/motion-bundler:23:in `<main>'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
        from /Users/kbsj/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```

Using  Rake Build

```
rake build
rake aborted!
NameError: uninitialized constant Faraday::Adapter::EMSynchrony::EMHttp
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.0/lib/faraday/adapter/em_synchrony.rb:6:in `<class:EMSynchrony>'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.0/lib/faraday/adapter/em_synchrony.rb:5:in `<class:Adapter>'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.0/lib/faraday/adapter/em_synchrony.rb:4:in `<module:Faraday>'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.0/lib/faraday/adapter/em_synchrony.rb:3:in `<top (required)>'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require/mocker/hooks.rb:21:in `require'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require/mocker/hooks.rb:21:in `require_with_mb_mock'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require/tracer/hooks.rb:33:in `block in require_with_mb_trace'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require/tracer/log.rb:42:in `register'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require/tracer/hooks.rb:32:in `require_with_mb_trace'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require/tracer/hooks.rb:66:in `autoload_with_mb_trace'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.0/lib/faraday/autoload.rb:27:in `block in autoload_all'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.0/lib/faraday/autoload.rb:26:in `each'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.0/lib/faraday/autoload.rb:26:in `autoload_all'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.0/lib/faraday/autoload.rb:53:in `<class:Adapter>'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.0/lib/faraday/autoload.rb:51:in `<module:Faraday>'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.0/lib/faraday/autoload.rb:1:in `<top (required)>'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require/mocker/hooks.rb:21:in `require'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require/mocker/hooks.rb:21:in `require_with_mb_mock'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require/tracer/hooks.rb:33:in `block in require_with_mb_trace'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require/tracer/log.rb:42:in `register'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require/tracer/hooks.rb:32:in `require_with_mb_trace'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.0/lib/faraday.rb:80:in `block in require_libs'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.0/lib/faraday.rb:79:in `each'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.0/lib/faraday.rb:79:in `require_libs'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.0/lib/faraday.rb:244:in `<module:Faraday>'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.0/lib/faraday.rb:16:in `<top (required)>'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require/mocker/hooks.rb:21:in `require'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require/mocker/hooks.rb:21:in `require_with_mb_mock'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require/tracer/hooks.rb:33:in `block in require_with_mb_trace'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require/tracer/log.rb:42:in `register'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require/tracer/hooks.rb:32:in `require_with_mb_trace'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/redditkit-1.0.1/lib/redditkit/client.rb:1:in `<top (required)>'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require/mocker/hooks.rb:21:in `require'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require/mocker/hooks.rb:21:in `require_with_mb_mock'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require/tracer/hooks.rb:33:in `block in require_with_mb_trace'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require/tracer/log.rb:42:in `register'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require/tracer/hooks.rb:32:in `require_with_mb_trace'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/redditkit-1.0.1/lib/redditkit.rb:1:in `<top (required)>'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require/mocker/hooks.rb:21:in `require'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require/mocker/hooks.rb:21:in `require_with_mb_mock'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require/tracer/hooks.rb:33:in `block in require_with_mb_trace'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require/tracer/log.rb:42:in `register'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require/tracer/hooks.rb:32:in `require_with_mb_trace'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/bundler-1.6.5/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/bundler-1.6.5/lib/bundler/runtime.rb:72:in `each'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/bundler-1.6.5/lib/bundler/runtime.rb:72:in `block in require'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/bundler-1.6.5/lib/bundler/runtime.rb:61:in `each'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/bundler-1.6.5/lib/bundler/runtime.rb:61:in `require'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/bundler-1.6.5/lib/bundler.rb:132:in `require'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler.rb:83:in `block in tracer_require'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require.rb:14:in `block (2 levels) in mock_and_trace'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require.rb:21:in `block in trace'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require/tracer.rb:18:in `yield'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require.rb:20:in `trace'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require.rb:13:in `block in mock_and_trace'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require.rb:27:in `block in mock'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require/mocker.rb:13:in `yield'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require.rb:26:in `mock'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler/require.rb:12:in `mock_and_trace'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler.rb:80:in `tracer_require'
/Users/kbsj/.rvm/gems/ruby-2.1.2/gems/motion-bundler-0.2.1/lib/motion-bundler.rb:23:in `block in setup'
/Library/RubyMotionPre/lib/motion/project/config.rb:110:in `call'
/Library/RubyMotionPre/lib/motion/project/config.rb:110:in `block in setup'
/Library/RubyMotionPre/lib/motion/project/config.rb:110:in `each'
/Library/RubyMotionPre/lib/motion/project/config.rb:110:in `setup'
/Library/RubyMotionPre/lib/motion/project/app.rb:66:in `config'
/Library/RubyMotionPre/lib/motion/project/template/android.rb:37:in `block in <top (required)>'
/Users/kbsj/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/Users/kbsj/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => build
(See full trace by running task with --trace)
```

**Comment by jeremiahlukus** [comment]
Same error still.
